#!/usr/bin/env python3
"""
Nexis Games — Bundle Build Tool
===============================
Re-encrypts /src/core.js into /app/core.dat using the XOR + base64
scheme expected by /app/loader.js.

Usage
-----
    python3 tools/build.py

Run this any time you edit /src/core.js. /data/games.js is plaintext and
does NOT need re-building.
"""
import base64, os, sys, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC  = ROOT / "src"  / "core.js"
DAT  = ROOT / "app"  / "core.dat"
KEY  = "N3xis-G@meS-2026-NexisGD-x7k9P"   # must match app/loader.js


def xor_encode(text: str, key: str) -> bytes:
    kb = key.encode("utf-8")
    tb = text.encode("utf-8")
    out = bytearray(len(tb))
    for i, ch in enumerate(tb):
        out[i] = ch ^ kb[i % len(kb)]
    return bytes(out)


def strip_comments(src: str) -> str:
    out = []
    for ln in src.split("\n"):
        if ln.lstrip().startswith("//"):
            continue
        out.append(ln)
    return re.sub(r"\n\s*\n+", "\n", "\n".join(out))


def main() -> int:
    if not SRC.exists():
        print(f"ERROR: missing {SRC}", file=sys.stderr)
        return 1

    raw = SRC.read_text()

    # If the source file has the editor preamble comment, strip it
    raw = re.sub(r"^/\*[\s\S]*?\*/\s*", "", raw, count=1)

    minified = strip_comments(raw)
    enc      = xor_encode(minified, KEY)
    b64      = base64.b64encode(enc).decode("ascii")
    chunks   = "\n".join(b64[i:i + 80] for i in range(0, len(b64), 80))

    DAT.write_text(
        "# NEXIS-GAMES-BUNDLE v1 // Encrypted Application Core\n"
        "# Do NOT edit this file. Edit /src/core.js and run tools/build.py.\n"
        "# Contents below are XOR-encrypted, base64-armoured.\n"
        "---BEGIN-NEXIS-CORE---\n"
        f"{chunks}\n"
        "---END-NEXIS-CORE---\n"
    )

    print(f"OK: wrote {DAT.relative_to(ROOT)}  ({len(b64):,} chars base64)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
